DELETE FROM CATEGORY;
DELETE FROM PRODUCT;
DELETE FROM TB_ORDER;
DELETE FROM ORDER_ITEM;

INSERT INTO CATEGORY (NAME) VALUES ('TEST CATEGORY 1');
INSERT INTO CATEGORY (NAME) VALUES ('TEST CATEGORY 2');
INSERT INTO CATEGORY (NAME) VALUES ('TEST CATEGORY 3');

INSERT INTO PRODUCT  (NAME, DESCRIPTION, PRICE, STOCK_QUANTITY, CATEGORY_ID) VALUES ('TEST PRODUCT 1', 'TEST PRODUCT 1', 10, 10, 1);
INSERT INTO PRODUCT  (NAME, DESCRIPTION, PRICE, STOCK_QUANTITY, CATEGORY_ID) VALUES ('TEST PRODUCT 2', 'TEST PRODUCT 2', 20, 20, 1);
INSERT INTO PRODUCT  (NAME, DESCRIPTION, PRICE, STOCK_QUANTITY, CATEGORY_ID) VALUES ('TEST PRODUCT 3', 'TEST PRODUCT 3', 30, 30, 2);
INSERT INTO PRODUCT  (NAME, DESCRIPTION, PRICE, STOCK_QUANTITY, CATEGORY_ID) VALUES ('TEST PRODUCT 4', 'TEST PRODUCT 4', 40, 40, 2);
INSERT INTO PRODUCT  (NAME, DESCRIPTION, PRICE, STOCK_QUANTITY, CATEGORY_ID) VALUES ('TEST PRODUCT 5', 'TEST PRODUCT 5', 50, 50, 3);

INSERT INTO TB_ORDER (TOTAL_AMOUNT, USER_ID) VALUES (140, 1);

INSERT INTO ORDER_ITEM  (QUANTITY, AMOUNT, PRODUCT_ID, ORDER_ID) VALUES (1, 10, 1, 1);
INSERT INTO ORDER_ITEM  (QUANTITY, AMOUNT, PRODUCT_ID, ORDER_ID) VALUES (2, 40, 2, 1);
INSERT INTO ORDER_ITEM  (QUANTITY, AMOUNT, PRODUCT_ID, ORDER_ID) VALUES (3, 90, 3, 1);